### ISSUE TITLE
Asks to install java

### ISSUE THREAD

**Issue by ScytheRyder** [xxomega77xx/Omegas-Wizards-Alpha-Launcher#1]
When launching though your launcher i get this error https://gyazo.com/0456603d09cfd2e220fac2dea58d1011
i have java upto date on this computer. have also tryed running as admin same issue

**Comment by xxomega77xx** [comment]
@ScytheRyder Can you provide what version of java you have installed?

**Comment by ScytheRyder** [comment]
Version 8 Update 251 (build 1.8.0_251-b08)

**Comment by xxomega77xx** [comment]
@ScytheRyder is that the 64 bit or 32 bit version of java? Also, assuming you are running windows 10?

**Comment by ScytheRyder** [comment]
Should be a 64bit and yeah windows 10

**Comment by xxomega77xx** [comment]
Ah ok, that would be why, I did not account for the 64-bit version, see if hitting yes and downloading the 32bit will let it go through and I will complete an update to account for the 64-bit version.

**Comment by ScytheRyder** [comment]
I gave it a fresh install and that seemed to fix the issue

**Comment by ScytheRyder** [comment]
yeah so that fresh install would of done the 32-bit version then?

**Comment by xxomega77xx** [comment]
For Tracking Purposes: This issue is present due to user having 64-bit java, the application will need to be updated to account for 64-bit java.

**Comment by xxomega77xx** [comment]
Issue resolved
